#!/bin/bash
# Date : v.2 - Quarta Feira, 02:51, 30 Setembro 2015 | coded by m4dd0x & rub3n S1lv4; 
# Date : v.3 - Mail Notification
echo "    ( _ )  	";
echo "   } 6 6 {        ";
echo "  ==. Y ,==         +-++-++-++-+ +-++-++-++-++-++-+  ";
echo "    /^^^\  .        |C||H||A||T| |S||E||R||V||E||R|  ";
echo "   /     \  )       +-++-++-++-+ +-++-++-++-++-++-+  ";
echo "  (  )-(  )/             P0w3rD by n3tC4t GNU";
echo " -----------   ";
echo "irssi@hotmail.com | Setembro 2015 | coded by MrX & MrY"
echo "Bom dia Mestre, deseja enviar email com o IP publico do servidor?(y/n)" 
read IP
if [ $IP = y ]; then
wget http://ipinfo.io/ip -qO - > ipublico.txt
ifconfig > iplan.txt
#mail -s "NCserver UP" mail@live.com.pt < ipublico.txt  
#mail -s "NCserver UP" mail@live.com.pt < iplan.txt
fi
while true; do read -n30 ui; echo $ui |openssl enc -aes-256-ctr -a -k PA3leFl0d3.t3; done | nc -k -l -p 8877 | while read so; do decoded_so=`echo "$so"| openssl enc -d -a -aes-256-ctr -k PA3leFl0d3.t3`; echo -e "\007" && echo -e "Recebido: $decoded_so"; done

